### ISSUE TITLE
Setting things up in HA

### ISSUE THREAD

**Issue by NathanLKing** [Nerivec/SmartHomeEnhanced#1]
Thank you for sharing all of your setup and files. Much appreciated.

I'm currently looking at integrating this into my HA and in particular voice.

I assume that I add code into my main configuration.yaml a reference to each of your configuration.yaml in their folders
E.g. !include /VoiceIntents/configuration.yaml

Thanks mate.

**Comment by Nerivec** [comment]
Include will work, just [be careful how you include it, and modify as needed](https://www.home-assistant.io/docs/configuration/splitting_configuration/).
You can also just copy the content "as-is" at the bottom of your main `configuration.yaml`.
